name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ next, master ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Start MongoDB
        uses: supercharge/mongodb-github-action@1.8.0
        with:
          mongodb-username: root
          mongodb-password: root
          mongodb-db: lightup

      - name: Build Application server
        working-directory: ./applications/server/src
        run: go build .
      
      - name: Unitest Application server
        working-directory: ./applications/server
        run: go test -v ./src/...

      - name: Start Application server
        working-directory: ./applications/server/src
        run: |
          go run . &
          sleep 5


      - name: Ping Application server
        uses: jtalk/url-health-check-action@v2
        with:
          url: 'http://localhost:4321/ping'
          follow-redirect: true
          max-attempts: 3
          retry-delay: 5s
          retry-all: fals